// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"github.com/google/wire"
	"github.com/manhhung2111/go-redis/internal/command"
	"github.com/manhhung2111/go-redis/internal/server"
	"github.com/manhhung2111/go-redis/internal/storage"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, error) {
	store := storage.NewStore()
	iRedis := command.NewRedis(store)
	serverServer := server.NewServer(iRedis)
	return serverServer, nil
}

// wire.go:

var WireSet = wire.NewSet(storage.WireSet, command.WireSet, server.WireSet)
